
name: Build for iOS

on:
  workflow_dispatch:
      
jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check Xcode
        run: ls $(xcrun --sdk iphoneos --show-sdk-path)
    
      - name: Install dependencies
        run: brew install zig
        
      - name: Check Xcode
        run: xcrun --sdk iphoneos --show-sdk-path
     
      - name: Build project
        run: zig build -Dtarget=aarch64-ios --sysroot "$(xcrun --sdk iphoneos --show-sdk-path)"

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: zig-out
          path: zig-out
